### ISSUE TITLE
Suggestion: React Native

### ISSUE THREAD

**Issue by laszlolm** [TryGhost/Ghost-iOS#1]
Are there any words against using React Native for the iOS / Android version of the app?

**Comment by JohnONolan** [comment]
No objections for the iOS version - would be interested to hear about what's possible here and if anyone else might be up for contributing with an approach like this :)

**Comment by arjunkomath** [comment]
I can contribute if its an RN project 👍

**Comment by Playrom** [comment]
I strongly disapprove using RN, unless the android version is already implemented with it

It's better to use the native apis in order to reduce the app size, improve performance, and adopt fast all the new functionalities...

Btw I can contribute if we choose to use Swift

**Comment by laszlolm** [comment]
@Playroom I can't agree with you. The performance is almost identical to Swift. Check out this article from months ago and since then they have improved it:
https://medium.com/the-react-native-log/comparing-the-performance-between-native-ios-swift-and-react-native-7b5490d363e2

If the performance and size increase would be so significant, Skype, Discord, Facebook and Tesla wouldn't be using it.

Your statement is true in 2016, not 2017. Especially for non-animation-heavy apps like Ghost will be

**Comment by laszlolm** [comment]
In fact, in most cases Swift uses more memory than React native and by this becomes laggy on older devices

**Comment by laszlolm** [comment]
Also please explain what you mean by "adopt new functionalities", I don't understand which functionalities you mean that are not available with RN but available with Swift

**Comment by arjunkomath** [comment]
@Playrom Also, we can have faster iterations and prototyping using React Native.

**Comment by JohnONolan** [comment]
Open discussion here is very welcome - but let's make sure it continues to remain civil. If this devolves into a holy war of React-v-Swift then I'll just lock the issue. Aint nobody got time for that.

Again: No problems at all so far. I just want to make sure it stays that way.

Different approaches to building iOS apps are really interesting, and I really enjoy hearing about all the ways in which we could approach this project. 

So far I've chatted to @laszlolm directly about why React Native might be a good fit for the project, and he makes a lot of really compelling points. 

I have to say, the notion of having the project be based in JS is really attractive for a team which is made of JS engineers and rooted in the JS community. Naturally we have a lot more skills and a lot more friends who know JavaScript than we have skills or friends who know Swift. That's not a technical consideration, but one of longevity. With community projects it's always important to ask: How easy it going to be to find maintainers over the life of the project?

I haven't heard anyone mention yet: Are there any shortcomings to RN which would make native Swift a demonstrably better choice / outweighing the considerations above?

**Comment by laszlolm** [comment]
@JohnONolan 
Re Civil war:, I am very happy to agree to developing this project in Swift if the reasons to why are specific enough, I just didn't feel that way, sorry if my comments were offensive, I didn't mean it that way, just wanted to clarify

Re Shortcomings: Animations and GPU-intense apps (like games, 3D stuff), in this specific app I don't see any aspect where RN would be a worse choice than Swift. For a game or something super animated I wouldn't recommend it.

**Comment by Playrom** [comment]
Re Civil War: in fact Slack, Discord, and many others are very very low performing apps, that create a lot of frustrations  among the users... and to make a point in the past every one was excited about using Java in order to have one code for all the platforms, meanwhile today java multi-platform apps suck. So the fancy new tecnology to "save code" may not be the optimal one :)

Btw I don't want to start a  long discussion between to completely different kind of approach, @JohnONolan is right when he said that all the contributors of Ghost know JS , so maybe it is the right path , in order to accept contributions by the Ghost Core Team 👍 

I can help with the Swift part of the project, and with the React views composition, but I'd prefer not take part in the development usage of Redux, React-Router etc... I have the worst nightmares while creating some Isomorphic web apps  those past summers 😂

**Comment by laszlolm** [comment]
@Playrom Slack is not using RN (and still gets stuck more than Discord for me personally, but this is just a personal observation). I haven't heard anyone complaining about the Discord iOS app within 2017, can you reference any threads on this issue? Something that's recurring among users?

About Redux / React-Router I believe we either start a discussion and choose the right technology for the product or later we can refactor when there are more active contributors.

And we will need some swift hands (pun intended) working on the project if we need to write bridges between RN and Swift, for example for animations (if we need anything special)

**Comment by JohnONolan** [comment]
Sounds to me like there's actually more to agree on here than to disagree on - either way we would need as much help as possible on the swift side :)

**Comment by benaubin** [comment]
Just weighing in, another Open Source project, [Habitica](https://github.com/HabitRPG/habitica-ios) originally used Angular and Cordova to build their project. They eventually migrated to a pure Objective-C/Switch approach. Their core team are JS specialists.

**Comment by JohnONolan** [comment]
Heard many similar horror stories about phonegap and corodova and the various other things in between which are all hybrid/html5 apps and not truly native. 

This isn't my area of expertise but so far my understanding is that React Native compiles directly to Swift as a native app without many compromises beyond graphical performance, which is why it's being used for the official iOS apps of Facebook, Instagram, Airbnb, Tesla, Skype and UberEats amongst others. 

Source 1: https://facebook.github.io/react-native/
Source 2: https://facebook.github.io/react-native/showcase.html

**Comment by laszlolm** [comment]
Let me correct @JohnONolan, React Native does not compile to Swift / Obj-C, it communicates with low level Objective-C modules (not Swift is important, performance increase over swift) so in vague terms we can say it compiles to ObjC but actually it doesn't, just every module has Obj-C background, some newer ones have Swift but its better to use the objc ones for really high performance

**Comment by laszlolm** [comment]
Reference for the newcomers / Swift devs who aren't familiar with RN: https://facebook.github.io/react-native/docs/javascript-environment.html

**Comment by laszlolm** [comment]
There is also this library I would propose to use, https://expo.io -- this gives extra performance increase by compiling almost everything into native

**Comment by AustinPaquette** [comment]
Starting to get into react-native myself for a personal project so if something is started I'd be following and probably contributing bits and pieces in ever-so-often.

**Comment by arjunkomath** [comment]
@JohnONolan I couldn't find the write APIs documentation for Ghost, it it available somewhere? I'm planning on building a prototype in react native.

**Comment by laszlolm** [comment]
@arjunkomath I believe there should be a discussion about it before we start ad-hoc building apps. The underlying technology, future scalability etc is an important context

**Comment by mwanjajoel** [comment]
Coming from an iOS perspective, React Native is a good choice until its time to implement new native APIs into a project. This from my observation takes time. So the choice of whether Swift is a good choice depends on how fast the Ghost iOS Community would want to implement new iOS APIs as they are released of wait / do the React Native versions before implementing them.

**Comment by armartinez** [comment]
My 2 cents, really interesting conversation. I would choose Swift and I would love to contribute. I'm by no means experienced in either technology, but for what i've understood, RN works with some kind of iOS native Javascript interpreter (bridge) which can communicate with low level apis. This fact would make it slower than a pure compiled program in swift, and the results on CPU performance on the article linked by @laszlolm seem to support this idea. Memory and GPU performance differences on the article might be caused by optimisation that RN does which should be possible to implement in Swift, but again, just an opinion. Given the nature of a Ghost application and the good performance offered by RN, I don't think this would make a big difference with either choice. But I have to agree with @mwanjajoel on the benefits of being able to implement new apis faster with swift and if the Android app is already developed in Java then the cross-platform benefit of React Native is not really relevant.

**Comment by philipheinser** [comment]
@JohnONolan I startet working on an iOS App in React Native you can try it out: https://expo.io/@philipheinser/ghost-ios I would love to contribute to the project.

**Comment by jaderfeijo** [comment]
Having had a few years of experience working with multi-platform apps, as well as native ones developed in both Swift and Objective-C I can say that, long term, native is always a better choice. That is due to a few reasons, some of which have already been mentioned here, but for me at least, the most important of which is the ability to debug and reason about your code during development. Multi-platform frameworks, as thin a layer as they might add, always do add a layer, and this layer is not always easy to debug when things go wrong. Every time you add an abstraction onto your system you're adding another potential point of failure, and when things do go wrong, as they often do, you want to make sure that you have as few points of failure as possible into your system. Personally, I find that having an abstraction on top of which your entire app sits on, such as is the case with technologies like React Native or Xamarin for instance, will always not only add some overhead, but will be a source for problems and limitations in the long run.

In saying that, it is very possible that a Ghost app developed in React Native will never hit these potential limitations and failures, meaning React Native could turn out to be a great choice if you consider an already existing workforce that is familiar with javascript and ready to contribute to the project. It is however important to acknowledge that it is not all smooth sailing.

Personally, I am more than happy to contribute to this project whatever the decision in the end. I would certainly be able to contribute more if we went down the Swift route as I have much more experience with it than I do with React Native, but I'm willing to contribute either way.

**Comment by raybradley** [comment]
Agree full native is preferable to RN. Have forked and started a Swift client. APIs could do with documentation, tho ;)

**Comment by Caraveo** [comment]
A new layer increases complexity of the system yet might reduce the complexity of development and time.  After all who wants to code in binary?  Yet if you could would you?  I vote Swift.

**Comment by genebean** [comment]
@raybradley if you need any testers or if there is any place someone brand new to Swift can help out feel free to ping me. Happy to do what I can.

**Comment by raybradley** [comment]
@genebean that would be great. If you want to grab my fork and try running it from Xcode on the iOS simulator that would be a great place to start. It’s somewhat optimized for iPad this far, and tag support is missing, but at least see if you can get it to fly?

**Comment by Here21** [comment]
guys, I don't want to join the discussion about **RN OR NATIVE**

I use RN to help my company quickly build new business. I have one year of experience RN.

If you decide to use it, **I join**

**Comment by kyuknis** [comment]
I'm going to start working with Ghost tonight and see about working on some model/provider logic in a Swift playground that might be able to turn into a cocoapod for Swift Ghost development. While I haven't created an application with React Native, I've yet to see one that supports some basic functionality such as landscape view. This project should focus on a experience that takes advantage of all of a given platforms capabilities, not just the ones that all platforms have in common. This is especially true of iOS where all of the devices in the ecosystem share such a significant portion of iOS's capabilities.

**Comment by kyuknis** [comment]
@raybradley I’ll fork it in the morning and start poking at what you left off with. First thing would be to add some encapsulation to the models. Would you be OK if I implemented a Provider paradigm as a singleton for the models, similar to what is seen with common ng2 applications?

**Comment by kyuknis** [comment]
@raybradley GhostRESTClient could definitely be refactored to be a singleton. It seems to be instantiated all over the place in your models and serializers.

**Comment by raybradley** [comment]
I'm unfamiliar with ng2 or the Provider pattern, but def game for where you're headed with it, @kyuknis. I can take a crack at applying a Singleton refactor on GhostRESTClient. I hadn't yet spent much time on refactors or optimizations; just trying to get basic behaviors to work.

**Comment by raybradley** [comment]
That all sounds good, @kyuknis. I'm about to head into the mountains for a week but happy to jump on Slack on returning.

I don't have any kind of design documents, no. I was loosely modeling the UI on [Bear](http://www.bear-writer.com/) and nominally optimizing for iPad but not precluding phones. Native UISplitView seemed inadequate for the job, hence the multi-pane layout you're seeing in there. Happy to revisit, completely open to ideas, and, yes, would love to have a Real UI Designer™ take a crack at it.

Also worth looking at from both a UI, networking, and functional perspective is the [Android app](https://github.com/TryGhost/Ghost-Android), which @vickychijwani did a bang-up job on.

Wondering if @JohnONolan, et al, would be willing to stand up 

Don't feel obliged to use any of my fork...it was more me noodling than a bona fide effort. But if it's useful, great. And if I can help, great. It'd be cool to see a kick-ass iOS Ghost app in the world.

**Comment by kyuknis** [comment]
To everyone: I’ll be tackling this issue on a regular basis in my fork. I’m approaching 20 commits in so far. I’ll update it with roadmaps and objectives soon. Long story short I’m working on the data logic first, then I’ll go on to the UI. My goal is to launch along side the first stable and full featured Ghost API.

**Comment by itsaphel** [comment]
@kyuknis what's your progress on that app?

**Comment by kyuknis** [comment]
@itsaphel I’m waitinf on ghost-src to get more work done on authentication before I countinue. Most of thr application’s architecture has been set up, models created, web logic abstracted, etc. When they implement an auth functionality that is closer to what we will see when they get out of beta I will continue working on it. 

https://forum.ghost.org/t/status-of-authentication-for-ghost-api/3085

**Comment by sayem314** [comment]
I have done it in react-native. The app is available on AppStore and PlayStore, it's not free nor open-source however if the ghost team supports me I can open-source it and make it free for everyone. Search `Obsess for Ghost` on any store to download the app.

**Comment by laszlolm** [comment]
^ Grand example on how decisions get stuck for years cc @JohnONolan

**Comment by JohnONolan** [comment]
@laszlolm Grand example of how open source happens when people contribute by writing code, and being an abrasive asshole doesn't actually achieve any progress at all - it just makes people definitely not want to have anything to do with you.
